Repository cloudnative-pg/plugin-barman-cloud, pull requests merged in 2025-08, with the labels that each got.

#458 fix: check for empty WAL archive during WAL archiving
  internal/cnpgi/common/check.go
  internal/cnpgi/common/wal.go
  internal/cnpgi/restore/restore.go
Labels: bug, lgtm, size:M

#462 chore: fix typo `lastSuccussfulBackupTime`
  api/v1/objectstore_types.go
  config/crd/bases/barmancloud.cnpg.io_objectstores.yaml
  manifest.yaml
  web/docs/plugin-barman-cloud.v1.md
Labels: lgtm, size:S

#475 fix(unit-tests): metrics collect length
  internal/cnpgi/instance/metrics_test.go
Labels: lgtm, size:XS
